### ISSUE TITLE
Nice one man!

### ISSUE THREAD

**Issue by DrAGoniPenguin** [iMRCx/Skyblock-Fairy-Souls-ESP-Unbaneable-#3]
I found it in 5 seconds but good job
Very clean code
Good job on the releases for 'tards.
I won't say what it was but nice one

**Comment by Napoleon-ZoomberParts** [comment]
> I found it in 5 seconds but good job Very clean code Good job on the releases for 'tards. I won't say what it was but nice one

He literally skidded the token logger and you are praising him for doing so
  
IMPRESSED FAN NN LOL

**Comment by DrAGoniPenguin** [comment]
> > I found it in 5 seconds but good job Very clean code Good job on the releases for 'tards. I won't say what it was but nice one
> 
> He literally skidded the token logger and you are praising him for doing so
> 
> IMPRESSED FAN NN LOL

I'm not a fan...
Never even heard of this guy until I was looking for fairy souls, and I am perfectly aware of my surroundings thank you very much.
I respect your opinion, but I am not praising him for the code, I'm saying good job on trying to rat people.
I also posted it on reddit a few days ago asking people to find the rat as a game.
Also, I do know if this is skidded or not, I'm not too dumb okay.
